<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>quat_to_euler</name>
  <version>0.0.0</version>
  <description>Converts IMU quaterions to Euler angles.</description>
  <maintainer email="l.mudrich@leeds.ac.uk">Lenka Mudrich</maintainer>
  <maintainer email="a.j.blight@leeds.ac.uk">Andy Blight</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2</depend>
  <depend>tf2_ros</depend>
  <depend>tf2_geometry_msgs</depend>
  <depend>pipebot_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
