float64 turret_dir
float64 inspect_dir
# class ActionState(Enum):
# MANOSTATE_TIMEOUT = -3
# MANOSTATE_COMPLETED = -2
# MANOSTATE_STARTED = -1
# MANOSTATE_STOP = 0
# MANOSTATE_FORWARDING = 1
# MANOSTATE_INSPECTING = 2
# MANOSTATE_BACKWARDING = 3
# MANOSTATE_TURRET_REVERSING = 4
# MANOSTATE_LEFT_TURNING = 5
# MANOSTATE_RIGHT_TURNING = 6
# MANOSTATE_SELF_BALANCING = 7
# robot inspection direction: inspect_dir
# robot local manouvre direction: man_dir
float64 FORWARD = 1.0
float64 BACKWARD = -1.0
# Turret direction



 